build update
update the spark-streaming-kafka for Kafka 10

fixes to
1. NotSerializable exceptions due to logger ??
 2. NoClassDefFoundError for GenericRecord

tried this but still NotSerializable

https://stackoverflow.com/questions/29208844/apache-spark-logging-within-scala

had to remove logging to avoid NotSerializableException

fixed: "ConfigException: Missing required configuration "value.deserializer" which has no default value."
Now getting "The configured groupId is invalid"

(checkpoint) application now starts

code cleanup to hide Kafka specifics away
(todo) all these modified classes can be moved under KafkaDSL