build update
update the spark-streaming-kafka for Kafka 10

fixes to
1. NotSerializable exceptions due to logger ??
 2. NoClassDefFoundError for GenericRecord