build update
update the spark-streaming-kafka for Kafka 10

fixes to
1. NotSerializable exceptions due to logger ??
 2. NoClassDefFoundError for GenericRecord

tried this but still NotSerializable

https://stackoverflow.com/questions/29208844/apache-spark-logging-within-scala